"""empty message

Revision ID: 0e86ddfee76e
Revises: 8237c66a9936
Create Date: 2023-05-21 10:49:57.686857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e86ddfee76e'
down_revision = '8237c66a9936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_staff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
