"""empty message

Revision ID: 62641f842d32
Revises: 0e86ddfee76e
Create Date: 2023-05-21 12:53:42.675730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62641f842d32'
down_revision = '0e86ddfee76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_staff')

    # ### end Alembic commands ###
